"""add order payment_status and payment_reference

Revision ID: 084ab726d063
Revises: c4f9a3e18b25
Create Date: 2026-08-29 00:59:40.582419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084ab726d063'
down_revision: Union[str, None] = 'c4f9a3e18b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills every existing order (all Cash on Delivery so
    # far) as unpaid, matching the ORM default — without it this fails on
    # any table that already has rows.
    op.add_column(
        'orders',
        sa.Column('payment_status', sa.String(length=20), nullable=False, server_default='unpaid'),
    )
    op.add_column('orders', sa.Column('payment_reference', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_reference')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
