"""add safepay_enabled to store settings

Revision ID: 0d2a787bf96d
Revises: 084ab726d063
Create Date: 2026-08-29 01:03:49.517269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2a787bf96d'
down_revision: Union[str, None] = '084ab726d063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default keeps the existing settings row's safepay_enabled
    # False (the ORM default) rather than failing the NOT NULL constraint.
    op.add_column(
        'store_settings',
        sa.Column('safepay_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'safepay_enabled')
    # ### end Alembic commands ###
