"""Add SEO fields

Revision ID: 0ecc43407f5c
Revises: 433958e164bb
Create Date: 2026-08-09 01:33:53.491791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ecc43407f5c'
down_revision: Union[str, None] = '433958e164bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('attribute_terms', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('categories', sa.Column('is_indexable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('categories', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('canonical_url', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('collections', sa.Column('is_indexable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('collections', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('collections', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('collections', sa.Column('canonical_url', sa.String(length=500), nullable=True))
    op.add_column('collections', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('collections', 'product_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('order_items', 'product_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('orders', 'shipping_address',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_faqs_product'), table_name='product_faqs')
    op.add_column('product_variations', sa.Column('gtin', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_product_variations_gtin'), 'product_variations', ['gtin'], unique=False)
    op.add_column('products', sa.Column('is_indexable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('products', 'dimensions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('products', 'care_instructions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('products', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('products', 'care_instructions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('products', 'dimensions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('products', 'is_indexable')
    op.drop_index(op.f('ix_product_variations_gtin'), table_name='product_variations')
    op.drop_column('product_variations', 'gtin')
    op.create_index(op.f('ix_product_faqs_product'), 'product_faqs', ['product_id'], unique=False)
    op.alter_column('orders', 'shipping_address',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('order_items', 'product_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('collections', 'product_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('collections', 'updated_at')
    op.drop_column('collections', 'canonical_url')
    op.drop_column('collections', 'meta_description')
    op.drop_column('collections', 'meta_title')
    op.drop_column('collections', 'is_indexable')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'canonical_url')
    op.drop_column('categories', 'meta_description')
    op.drop_column('categories', 'meta_title')
    op.drop_column('categories', 'is_indexable')
    op.alter_column('attribute_terms', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('activity_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
