"""add image and is_verified_buyer to testimonials

Revision ID: 1e7d591d5bd0
Revises: 0d2a787bf96d
Create Date: 2026-09-01 10:58:59.241277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7d591d5bd0'
down_revision: Union[str, None] = '0d2a787bf96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('image', sa.String(length=500), nullable=True))
    # server_default backfills the existing row as False, matching the ORM
    # default — without it this fails on a table that already has rows.
    op.add_column(
        'testimonials',
        sa.Column('is_verified_buyer', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'is_verified_buyer')
    op.drop_column('testimonials', 'image')
    # ### end Alembic commands ###
