"""add instagram token to store settings

Revision ID: 37a56a3ce867
Revises: 1e7d591d5bd0
Create Date: 2026-09-03 15:35:51.789995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a56a3ce867'
down_revision: Union[str, None] = '1e7d591d5bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('instagram_access_token', sa.String(length=500), nullable=True))
    op.add_column('store_settings', sa.Column('instagram_token_refreshed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'instagram_token_refreshed_at')
    op.drop_column('store_settings', 'instagram_access_token')
    # ### end Alembic commands ###
