"""add guest checkout fields to orders

Revision ID: 61023f5f0bf6
Revises: 71079800fbc4
Create Date: 2026-02-12 20:40:41.280953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61023f5f0bf6'
down_revision: Union[str, None] = '71079800fbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('guest_first_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('guest_last_name', sa.String(length=100), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('orders', 'guest_last_name')
    op.drop_column('orders', 'guest_first_name')
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###
